.SUFFIXES: .tpl .obj
CC = g++ -mno-cygwin
LL = $(CC) 
CFLAGS = -Wno-deprecated -fpermissive -c  -I. -I/admodel/include -D__GNUDOS__ -DOPT_LIB -Dlinux -DUSE_LAPLACE
 
kfsst: kfsst.cpp kfsst.obj yrmonday.obj azimuth.obj banner.obj solstice.obj
	$(LL) kfsst.obj yrmonday.obj banner.obj azimuth.obj solstice.obj -o kfsst -L/admodel/lib -ldf1b2o -ladmod -ladt -lado -ldf1b2o -ladmod -ladt -lado 

.cpp.obj:
	$(CC) $(CFLAGS) $< -o$*.obj

.tpl.cpp:
	/admodel/bin/tpl2cpp $*


