.SUFFIXES: .tpl .obj
CC = g++ -mno-cygwin
LL = $(CC)
CFLAGS = -Wno-deprecated -fpermissive -c  -I. -I/admodel/include -D__GNUDOS__ -DOPT_LIB -Dlinux -DUSE_LAPLACE -O3

ukf: ukf.cpp ukf.obj 
	$(LL) ukf.obj -o ukf -L/admodel/lib -ldf1b2o -ladmod -ladt -lado -ldf1b2o -ladmod -ladt -lado

prepro: prepro.cpp prepro.obj 
	$(LL) prepro.obj -o prepro -L/admodel/lib -ldf1b2o -ladmod -ladt -lado -ldf1b2o -ladmod -ladt -lado

.cpp.obj:
	$(CC) $(CFLAGS) $< -o$*.obj

.tpl.cpp:
	/admodel/bin/tpl2cpp $*
