ukfsst: ukfsst.tpl yrmonday.cpp azimuth.cpp banner.cpp solstice.cpp
	CXXFLAGS=-fpermissive admb ukfsst.tpl yrmonday.cpp azimuth.cpp banner.cpp solstice.cpp
clean:
	@rm -vf ukfsst *.o ukfsst.cpp ukfsst.htp
